name: Build and Publish

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - uses: earthly/actions-setup@v1
      with:
        version: v0.8.9
  
    - name: Check Out Repo
      uses: actions/checkout@v3

    - name: Lint
      run: earthly +lint

    - name: Build
      run: earthly +build

    - name: Test
      run: earthly +test

  release:
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: v0.8.9

    - name: Check Out Repo
      uses: actions/checkout@v3

    - name: Publish
      run: earthly --secret "npm_token=${NPM_TOKEN}" +publish --VERSION=${{ github.ref_name }}
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}